import Foundation
#if canImport(FoundationModels)
import FoundationModels
#endif

#if canImport(FoundationModels)
@available(macOS 26.0, *)
@Generable
struct EmailInsight {
    @Guide(description: "2-3 sentence summary of the email content")
    var summary: String
    @Guide(description: "Required action from the recipient, if any. nil if purely informational")
    var actionNeeded: String?
    @Guide(description: "Deadline or time-sensitive date mentioned, if any")
    var deadline: String?
    @Guide(description: "Sentiment: positive, neutral, negative, or urgent")
    var sentiment: String
}
#endif

struct EmailInsightSnapshot: Sendable {
    var summary: String?
    var actionNeeded: String?
    var deadline: String?
    var sentiment: String?
}

@MainActor
final class SummaryService {
    static let shared = SummaryService()

    private static let maxCacheSize = 200

    var accountID: String = "" {
        didSet {
            if oldValue != accountID {
                cache.removeAll()
                aiGenerated.removeAll()
                accessOrder.removeAll()
            }
        }
    }

    private var cache: [String: String] = [:]
    /// Tracks which summaries were generated by Apple Intelligence vs fallback.
    private var aiGenerated: Set<String> = []
    /// Tracks key access order for LRU eviction (oldest first).
    private var accessOrder: [String] = []

    private init() {}

    func cachedSummary(for email: Email) -> String? {
        guard let key = AIServiceHelpers.cacheKey(for: email) else { return nil }
        guard let value = cache[key] else { return nil }
        // Move to end of access order (most recently used)
        accessOrder.removeAll { $0 == key }
        accessOrder.append(key)
        return value
    }

    func isAIGenerated(for email: Email) -> Bool {
        guard let key = AIServiceHelpers.cacheKey(for: email) else { return false }
        return aiGenerated.contains(key)
    }

    func summary(for email: Email) -> AsyncStream<String> {
        AsyncStream { continuation in
            let task = Task {
                if let key = AIServiceHelpers.cacheKey(for: email), let cached = cache[key] {
                    // Track access for LRU eviction
                    accessOrder.removeAll { $0 == key }
                    accessOrder.append(key)
                    continuation.yield(cached)
                    continuation.finish()
                    return
                }

                if #available(macOS 26.0, *) {
                    #if canImport(FoundationModels)
                    await generateWithFoundationModels(email: email, continuation: continuation)
                    #else
                    yieldFallback(email: email, continuation: continuation)
                    #endif
                } else {
                    yieldFallback(email: email, continuation: continuation)
                }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    #if canImport(FoundationModels)
    @available(macOS 26.0, *)
    private func generateWithFoundationModels(email: Email, continuation: AsyncStream<String>.Continuation) async {
        do {
            let instructions = Instructions("""
            You are an email assistant inside a macOS email client. \
            The user is hovering over an email and wants a quick glanceable summary. \
            Rules:
            - Write 2-3 short sentences max.
            - Lead with the key intent or action requested, not a description of the email.
            - If there's a deadline, date, amount, or link, mention it.
            - If the email is a newsletter/promo, say what it's about in one line.
            - If it's a reply thread, focus on the latest message only.
            - Never start with "This email..." or "The sender...". Be direct.
            - Use the same language as the email body.
            - Strip any signature, disclaimer or legal notice from consideration.
            """)
            let session = LanguageModelSession(instructions: instructions)

            var context = "From: \(email.sender.name)"
            if !email.recipients.isEmpty {
                let to = email.recipients.prefix(3).map(\.name).joined(separator: ", ")
                context += "\nTo: \(to)"
            }
            context += "\nSubject: \(email.subject)"
            context += "\nDate: \(email.date.formatted(date: .abbreviated, time: .shortened))"
            if email.hasAttachments {
                let names = email.attachments.prefix(3).map(\.name).joined(separator: ", ")
                context += "\nAttachments: \(names)"
            }

            let body = AIServiceHelpers.cleanedPreview(from: email)
            let prompt = """
            \(context)

            \(body)
            """

            var accumulated = ""
            let response = session.streamResponse(to: prompt)
            for try await snapshot in response {
                accumulated = snapshot.content
                continuation.yield(accumulated)
            }

            if let key = AIServiceHelpers.cacheKey(for: email) {
                cache[key] = accumulated
                aiGenerated.insert(key)
                accessOrder.removeAll { $0 == key }
                accessOrder.append(key)
                trimCacheIfNeeded()
            }
            continuation.finish()
        } catch {
            yieldFallback(email: email, continuation: continuation)
        }
    }
    #endif

    private func yieldFallback(email: Email, continuation: AsyncStream<String>.Continuation) {
        let fallback = AIServiceHelpers.cleanedPreview(from: email)
        if let key = AIServiceHelpers.cacheKey(for: email) {
            cache[key] = fallback
            accessOrder.removeAll { $0 == key }
            accessOrder.append(key)
            trimCacheIfNeeded()
        }
        continuation.yield(fallback)
        continuation.finish()
    }

    private func trimCacheIfNeeded() {
        guard cache.count > Self.maxCacheSize else { return }
        let removeCount = cache.count / 2
        let keysToRemove = accessOrder.prefix(removeCount)
        for key in keysToRemove {
            cache.removeValue(forKey: key)
            aiGenerated.remove(key)
        }
        accessOrder.removeFirst(keysToRemove.count)
    }

    #if canImport(FoundationModels)
    @available(macOS 26.0, *)
    func insight(for email: Email) -> AsyncStream<EmailInsightSnapshot> {
        AsyncStream { continuation in
            let task = Task {
                do {
                    let instructions = Instructions("""
                    Analyze this email and provide a structured summary. \
                    Focus on what matters: what is it about, what action is needed, any deadlines.
                    """)
                    let session = LanguageModelSession(instructions: instructions)
                    let body = AIServiceHelpers.cleanedPreview(from: email)
                    let truncated = String(body.prefix(10000))
                    let prompt = "From: \(email.sender.name)\nSubject: \(email.subject)\n\n\(truncated)"
                    let response = session.streamResponse(to: prompt, generating: EmailInsight.self)
                    for try await partial in response {
                        continuation.yield(EmailInsightSnapshot(
                            summary: partial.content.summary,
                            actionNeeded: partial.content.actionNeeded,
                            deadline: partial.content.deadline,
                            sentiment: partial.content.sentiment
                        ))
                    }
                    continuation.finish()
                } catch { continuation.finish() }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }
    #endif
}
