import Foundation
#if canImport(FoundationModels)
import FoundationModels
private import Contacts
#endif

#if canImport(FoundationModels)
@Generable
struct EmailInsight {
    @Guide(description: "2-3 sentence summary of the email content")
    var summary: String
    @Guide(description: "Required action from the recipient, if any. nil if purely informational")
    var actionNeeded: String?
    @Guide(description: "Deadline or time-sensitive date mentioned, if any")
    var deadline: String?
    @Guide(description: "Sentiment: positive, neutral, negative, or urgent")
    var sentiment: String
}

struct ContactLookupTool: Tool {
    let name = "lookupContact"
    let description = "Look up a contact by email address to find their name and relationship"

    @Generable
    struct Arguments {
        @Guide(description: "Email address to look up")
        var emailAddress: String
    }

    func call(arguments: Arguments) async throws -> String {
        let store = CNContactStore()
        let keysToFetch: [CNKeyDescriptor] = [
            CNContactGivenNameKey as CNKeyDescriptor,
            CNContactFamilyNameKey as CNKeyDescriptor,
            CNContactOrganizationNameKey as CNKeyDescriptor,
            CNContactJobTitleKey as CNKeyDescriptor
        ]

        let predicate = CNContact.predicateForContacts(matchingEmailAddress: arguments.emailAddress)

        guard let contact = (try? store.unifiedContacts(matching: predicate, keysToFetch: keysToFetch)).flatMap({ $0.first }) else {
            return "Contact not found for \(arguments.emailAddress)"
        }

        var parts: [String] = []
        let fullName = [contact.givenName, contact.familyName]
            .filter { !$0.isEmpty }
            .joined(separator: " ")
        if !fullName.isEmpty {
            parts.append("Name: \(fullName)")
        }
        if !contact.organizationName.isEmpty {
            parts.append("Organization: \(contact.organizationName)")
        }
        if !contact.jobTitle.isEmpty {
            parts.append("Job title: \(contact.jobTitle)")
        }

        return parts.isEmpty
            ? "Contact not found for \(arguments.emailAddress)"
            : parts.joined(separator: ", ")
    }
}
#endif

struct EmailInsightSnapshot: Sendable {
    var summary: String?
    var actionNeeded: String?
    var deadline: String?
    var sentiment: String?
}

@MainActor
final class SummaryService {
    static let shared = SummaryService()

    var accountID: String = "" {
        didSet {
            if oldValue != accountID {
                cache.removeAll()
                aiGenerated.removeAll()
            }
        }
    }

    private let cache = LRUCache<String, String>(maxSize: 200, evictionFraction: 0.5)
    /// Tracks which summaries were generated by Apple Intelligence vs fallback.
    private var aiGenerated: Set<String> = []

    private init() {}

    func isAIGenerated(for email: Email) -> Bool {
        let key = AIServiceHelpers.cacheKey(for: email)
        return aiGenerated.contains(key)
    }

    func summary(for email: Email) -> AsyncStream<String> {
        AsyncStream { continuation in
            let task = Task {
                let key = AIServiceHelpers.cacheKey(for: email)
                if let cached = cache[key] {
                    continuation.yield(cached)
                    continuation.finish()
                    return
                }

                #if canImport(FoundationModels)
                await generateWithFoundationModels(email: email, continuation: continuation)
                #else
                yieldFallback(email: email, continuation: continuation)
                #endif
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    #if canImport(FoundationModels)
    private func generateWithFoundationModels(email: Email, continuation: AsyncStream<String>.Continuation) async {
        do {
            let instructions = Instructions("""
            You are an email assistant inside a macOS email client. \
            The user is hovering over an email and wants a quick glanceable summary. \
            Rules:
            - Write 2-3 short sentences max.
            - Lead with the key intent or action requested, not a description of the email.
            - If there's a deadline, date, amount, or link, mention it.
            - If the email is a newsletter/promo, say what it's about in one line.
            - If it's a reply thread, focus on the latest message only.
            - Never start with "This email..." or "The sender...". Be direct.
            - Use the same language as the email body.
            - Strip any signature, disclaimer or legal notice from consideration.
            """)
            let session = LanguageModelSession(tools: [ContactLookupTool()], instructions: instructions)

            var context = "From: \(email.sender.name)"
            if !email.recipients.isEmpty {
                let to = email.recipients.prefix(3).map(\.name).joined(separator: ", ")
                context += "\nTo: \(to)"
            }
            context += "\nSubject: \(email.subject)"
            context += "\nDate: \(email.date.formatted(date: .abbreviated, time: .shortened))"
            if email.hasAttachments {
                let names = email.attachments.prefix(3).map(\.name).joined(separator: ", ")
                context += "\nAttachments: \(names)"
            }

            let body = AIServiceHelpers.cleanedPreview(from: email)
            let prompt = """
            \(context)

            \(body)
            """

            var accumulated = ""
            let response = session.streamResponse(to: prompt)
            for try await snapshot in response {
                accumulated = snapshot.content
                continuation.yield(accumulated)
            }

            let key = AIServiceHelpers.cacheKey(for: email)
            cache[key] = accumulated
            aiGenerated.insert(key)
            continuation.finish()
        } catch {
            yieldFallback(email: email, continuation: continuation)
        }
    }
    #endif

    private func yieldFallback(email: Email, continuation: AsyncStream<String>.Continuation) {
        let fallback = AIServiceHelpers.cleanedPreview(from: email)
        let key = AIServiceHelpers.cacheKey(for: email)
        cache[key] = fallback
        continuation.yield(fallback)
        continuation.finish()
    }

    #if canImport(FoundationModels)
    func insight(for email: Email) -> AsyncStream<EmailInsightSnapshot> {
        AsyncStream { continuation in
            let task = Task {
                do {
                    let instructions = Instructions("""
                    Analyze this email and provide a structured summary. \
                    Focus on what matters: what is it about, what action is needed, any deadlines.
                    """)
                    let session = LanguageModelSession(tools: [ContactLookupTool()], instructions: instructions)
                    let body = AIServiceHelpers.cleanedPreview(from: email)
                    let truncated = String(body.prefix(10000))
                    let prompt = "From: \(email.sender.name)\nSubject: \(email.subject)\n\n\(truncated)"
                    let response = session.streamResponse(to: prompt, generating: EmailInsight.self)
                    for try await partial in response {
                        continuation.yield(EmailInsightSnapshot(
                            summary: partial.content.summary,
                            actionNeeded: partial.content.actionNeeded,
                            deadline: partial.content.deadline,
                            sentiment: partial.content.sentiment
                        ))
                    }
                    continuation.finish()
                } catch { continuation.finish() }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }
    #endif
}
