import Foundation
#if canImport(FoundationModels)
import FoundationModels
#endif

#if canImport(FoundationModels)
@available(macOS 26.0, *)
@Generable
struct EmailInsight {
    @Guide(description: "2-3 sentence summary of the email content")
    var summary: String
    @Guide(description: "Required action from the recipient, if any. nil if purely informational")
    var actionNeeded: String?
    @Guide(description: "Deadline or time-sensitive date mentioned, if any")
    var deadline: String?
    @Guide(description: "Sentiment: positive, neutral, negative, or urgent")
    var sentiment: String
}
#endif

struct EmailInsightSnapshot: Sendable {
    var summary: String?
    var actionNeeded: String?
    var deadline: String?
    var sentiment: String?
}

@MainActor
final class SummaryService {
    static let shared = SummaryService()

    private static let maxCacheSize = 200

    var accountID: String = "" {
        didSet {
            if oldValue != accountID {
                cache.removeAll()
                aiGenerated.removeAll()
            }
        }
    }

    private var cache: [String: String] = [:]
    /// Tracks which summaries were generated by Apple Intelligence vs fallback.
    private var aiGenerated: Set<String> = []

    private init() {}

    func cachedSummary(for email: Email) -> String? {
        guard let key = cacheKey(for: email) else { return nil }
        return cache[key]
    }

    func isAIGenerated(for email: Email) -> Bool {
        guard let key = cacheKey(for: email) else { return false }
        return aiGenerated.contains(key)
    }

    func summary(for email: Email) -> AsyncStream<String> {
        AsyncStream { continuation in
            let task = Task {
                if let key = cacheKey(for: email), let cached = cache[key] {
                    continuation.yield(cached)
                    continuation.finish()
                    return
                }

                if #available(macOS 26.0, *) {
                    #if canImport(FoundationModels)
                    await generateWithFoundationModels(email: email, continuation: continuation)
                    #else
                    yieldFallback(email: email, continuation: continuation)
                    #endif
                } else {
                    yieldFallback(email: email, continuation: continuation)
                }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    #if canImport(FoundationModels)
    @available(macOS 26.0, *)
    private func generateWithFoundationModels(email: Email, continuation: AsyncStream<String>.Continuation) async {
        do {
            let instructions = Instructions("""
            You are an email assistant inside a macOS email client. \
            The user is hovering over an email and wants a quick glanceable summary. \
            Rules:
            - Write 2-3 short sentences max.
            - Lead with the key intent or action requested, not a description of the email.
            - If there's a deadline, date, amount, or link, mention it.
            - If the email is a newsletter/promo, say what it's about in one line.
            - If it's a reply thread, focus on the latest message only.
            - Never start with "This email..." or "The sender...". Be direct.
            - Use the same language as the email body.
            - Strip any signature, disclaimer or legal notice from consideration.
            """)
            let session = LanguageModelSession(instructions: instructions)

            var context = "From: \(email.sender.name)"
            if !email.recipients.isEmpty {
                let to = email.recipients.prefix(3).map(\.name).joined(separator: ", ")
                context += "\nTo: \(to)"
            }
            context += "\nSubject: \(email.subject)"
            context += "\nDate: \(email.date.formatted(date: .abbreviated, time: .shortened))"
            if email.hasAttachments {
                let names = email.attachments.prefix(3).map(\.name).joined(separator: ", ")
                context += "\nAttachments: \(names)"
            }

            let body = cleanedPreview(from: email)
            let prompt = """
            \(context)

            \(body)
            """

            var accumulated = ""
            let response = session.streamResponse(to: prompt)
            for try await snapshot in response {
                accumulated = snapshot.content
                continuation.yield(accumulated)
            }

            if let key = cacheKey(for: email) {
                cache[key] = accumulated
                aiGenerated.insert(key)
                trimCacheIfNeeded()
            }
            continuation.finish()
        } catch {
            yieldFallback(email: email, continuation: continuation)
        }
    }
    #endif

    private func yieldFallback(email: Email, continuation: AsyncStream<String>.Continuation) {
        let fallback = cleanedPreview(from: email)
        if let key = cacheKey(for: email) {
            cache[key] = fallback
            trimCacheIfNeeded()
        }
        continuation.yield(fallback)
        continuation.finish()
    }

    private func cleanedPreview(from email: Email) -> String {
        let text = email.body.isEmpty ? email.preview : email.body
        return text.cleanedForAI()
    }

    private func cacheKey(for email: Email) -> String? {
        email.gmailMessageID ?? email.id.uuidString
    }

    private func trimCacheIfNeeded() {
        if cache.count > Self.maxCacheSize {
            cache.removeAll()
            aiGenerated.removeAll()
        }
    }

    #if canImport(FoundationModels)
    @available(macOS 26.0, *)
    func insight(for email: Email) -> AsyncStream<EmailInsightSnapshot> {
        AsyncStream { continuation in
            let task = Task {
                do {
                    let instructions = Instructions("""
                    Analyze this email and provide a structured summary. \
                    Focus on what matters: what is it about, what action is needed, any deadlines.
                    """)
                    let session = LanguageModelSession(instructions: instructions)
                    let body = cleanedPreview(from: email)
                    let truncated = String(body.prefix(10000))
                    let prompt = "From: \(email.sender.name)\nSubject: \(email.subject)\n\n\(truncated)"
                    let response = session.streamResponse(to: prompt, generating: EmailInsight.self)
                    for try await partial in response {
                        continuation.yield(EmailInsightSnapshot(
                            summary: partial.content.summary,
                            actionNeeded: partial.content.actionNeeded,
                            deadline: partial.content.deadline,
                            sentiment: partial.content.sentiment
                        ))
                    }
                    continuation.finish()
                } catch { continuation.finish() }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    @available(macOS 26.0, *)
    func threadInsight(messages: [Email]) -> AsyncStream<EmailInsightSnapshot> {
        AsyncStream { continuation in
            let task = Task {
                do {
                    let instructions = Instructions("""
                    Analyze this email thread and provide a structured summary. \
                    Focus on the most recent developments and any required actions. \
                    Use the same language as the emails.
                    """)
                    let session = LanguageModelSession(instructions: instructions)

                    // Chain summarization: if >3 messages, summarize older ones first
                    let context: String
                    if messages.count > 3 {
                        let olderMessages = messages.dropLast(2)
                        let olderText = olderMessages.map { msg in
                            "From: \(msg.sender.name)\n\(msg.body.cleanedForAI().prefix(2000))"
                        }.joined(separator: "\n---\n")

                        // Summarize older messages into a paragraph
                        let summaryResponse = try await session.respond(
                            to: "Summarize this email history in one paragraph:\n\n\(String(olderText.prefix(8000)))"
                        )
                        let recentText = messages.suffix(2).map { msg in
                            "From: \(msg.sender.name)\nSubject: \(msg.subject)\n\(msg.body.cleanedForAI().prefix(3000))"
                        }.joined(separator: "\n---\n")

                        context = "Earlier context: \(summaryResponse.content)\n\nRecent messages:\n\(recentText)"
                    } else {
                        context = messages.map { msg in
                            "From: \(msg.sender.name)\nSubject: \(msg.subject)\n\(msg.body.cleanedForAI().prefix(3000))"
                        }.joined(separator: "\n---\n")
                    }

                    // Truncate to fit context window
                    let truncated = String(context.prefix(10000))
                    let response = session.streamResponse(to: truncated, generating: EmailInsight.self)
                    for try await partial in response {
                        continuation.yield(EmailInsightSnapshot(
                            summary: partial.content.summary,
                            actionNeeded: partial.content.actionNeeded,
                            deadline: partial.content.deadline,
                            sentiment: partial.content.sentiment
                        ))
                    }
                    continuation.finish()
                } catch {
                    continuation.finish()
                }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }
    #endif
}
